objects/Contact.object
<CustomObject>
    <fields>
        <fullName>test__c</fullName>
        <label>test</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/survey__c.object
<CustomObject>
    <label>survey</label>
    <nameField>
        <label>survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/test__c.object
<CustomObject>
    <label>test</label>
    <nameField>
        <label>test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>test</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/surveyHelper.cls
public class surveyHelper {
    public static void updateEmail(List<Survey__c>sList)
    {
        set<Id>contactName=new Set<Id>();
        List<Survey__c>updatedSurvey=new List<Survey__c>();
            for(Survey__c s:sList)
            {
                System.debug('Inside first loop');
                contactName.add(s.ContactEmail__c);
            }
        Map<Id,Contact>cMap=new Map<Id,Contact>([Select Email from Contact where Id IN :contactName]);
        for(Survey__c s:sList)
        {
              String Email=cMap.get(s.ContactEmail__c).Email;
              System.debug('Inside second loop ------');
              System.debug('email is-----'+s.Contact_Email__c);
              s.test__c=Email;
              System.debug('email after update  is-----'+s.test__c);
             
           
              
        }
        
      
        
        //System.debug('size'+updatedSurvey.Size());
        
        
        
        
    }

}