objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>College Campus</fullName>
                </value>
                <value>
                    <fullName>Hospital</fullName>
                </value>
                <value>
                    <fullName>Public Area</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/retrieveProperty.cls
public with sharing class retrieveProperty {
@AuraEnabled
    public static List<Property__c> getProperty() {
        List<Property__c> property =[SELECT Type__c, Name FROM Property__c];

        //Add isAccessible() check
        return property;
    }
    @AuraEnabled
    public static void deleteProperty(String Ids) {
        Delete [Select Id From Property__c where Id=:Ids];
        
    }


}